### ISSUE TITLE
cURL error 28

### ISSUE THREAD

**Issue by rebajz** [ericmartel/codeception-email-mailtrap#4]
Today i try add to codeception 2.2.0 - RC2 your module.

I doing everythink in help guide.

this is my test:
<?php
$I = new FunctionalTester($scenario);
$I->wantTo('i try delete all mail in my mailtrap box');
$I->deleteAllEmails();

In html output I have this error:
I delete all emails
cURL error 28: SSL connection timeout (see http://curl.haxx.se/libcurl/c/libcurl-errors.html) 

on this site is writen
CURLE_OPERATION_TIMEDOUT (28)
Operation timeout. The specified time-out period was reached according to the conditions. 

What can i do for correct testing?

**Comment by ericmartel** [comment]
Hi,

Are you sure Mailtrap is configured properly?  Did you configure both the token and the inbox?

**Comment by rebajz** [comment]
Hi,
today i create on mailtrap new, blank test profile... you can try, what you need...

in my functional.suite.yml i have:

```
class_name: FunctionalTester
modules:
    enabled:
        # add framework module here
        - \Helper\Functional
        - Mailtrap
    config:
        Mailtrap:
          api_token: 8f757a9fba91e649afe7017261e9d979
          inbox_id: 113128
```

in my mailCept.php i have:

```
<?php 
$I = new FunctionalTester($scenario);
$I->am('a member');
$I->wantTo('request a reset password link');

// First, remove all existing emails in the Mailtrap inbox
$I->deleteAllEmails();
```

i run test by:
vendor\bin\codecept run functional --html

my json:

```
{
    "require-dev": {
        "codeception/codeception":"2.2.0-RC2",
        "ericmartel/codeception-email": "^1.0",
        "ericmartel/codeception-email-mailtrap": "^1.0.4"
    }
}
```
